experiment_settings:
  mode: predict
  use_msa_server: false
  use_templates: false

data_module_args:
  batch_size: 1
  num_workers: 4
  num_workers_validation: 4

pl_trainer_args:
  devices: 1
  accelerator: gpu

model_update:
  presets: ["predict", "pae_enabled"]
  custom:
    settings:
      memory:
        eval:
          use_deepspeed_evo_attention: false
          use_lma: false
          use_mlx_attention: false
          use_mlx_triangle_kernels: false
          use_mlx_activation_functions: false
